# Generated by Django 4.0.4 on 2022-09-14 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_category', models.CharField(default='null', max_length=256, null=True, verbose_name='super_category')),
                ('name', models.CharField(max_length=256, verbose_name='category_name')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='created_at')),
                ('recently_modified_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('is_private', models.BooleanField(verbose_name=False)),
            ],
            options={
                'verbose_name': 'PostCategory',
                'db_table': 'PostCategory',
                'unique_together': {('parent_category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('contents', models.TextField(verbose_name='content')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='created_at')),
                ('recently_modified_at', models.DateTimeField(auto_now_add=True, verbose_name='recently_modified_at')),
                ('visited_at', models.PositiveIntegerField(default=0, verbose_name='visited')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='post', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='post', to='fuckf.postcategory', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Post',
                'db_table': 'Post',
            },
        ),
    ]
