# Generated by Django 4.0.4 on 2022-09-19 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuckf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='post',
            name='recently_modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='recently_modified_at'),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='postimage')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='fuckf.post')),
            ],
            options={
                'verbose_name': 'PostImages',
                'db_table': 'PostImages',
            },
        ),
    ]
